Adapt notebook to work with cinnabar0.3
OpenFreeEnergy/ExampleNotebooks pull request #88
Opened 2023-10-20 15:30 UTC by hannahbaumann

2023-10-20 17:08 UTC, IAlibay commented
@hannahbaumann could you add this folder to the CI command? We should try to have it run here too

2023-10-23 06:17 UTC, IAlibay requested changes
Thanks @hannahbaumann - couple of small things + CI

I wasn't able to run this locally on a fresh cinnabar install though :/

2023-10-23 06:17 UTC, IAlibay commented on plotting_rbfes_with_cinnabar/PlottingFreeEnergiesUsingCinnabar.ipynb
> -    "        'calculated_estimate': nodes[key]['exp_DG'],\n",
yikes, that was a bad typo 🙈 - Thanks for catching this!

2023-10-23 06:17 UTC, IAlibay commented on plotting_rbfes_with_cinnabar/PlottingFreeEnergiesUsingCinnabar.ipynb
> +      " 'lig_jmc_28': {'calculated_error': 0.07933473388119473,\n",
Could you do a 2d.p. truncation on the results writing so calculated & experimental are consistent? (lines 452-453 & 463-464)

2023-10-23 06:17 UTC, IAlibay commented on plotting_rbfes_with_cinnabar/PlottingFreeEnergiesUsingCinnabar.ipynb
> +   "cell_type": "code",
Could you delete this cell please?

2023-10-23 06:17 UTC, IAlibay commented on plotting_rbfes_with_cinnabar/PlottingFreeEnergiesUsingCinnabar.ipynb
> +    "from cinnabar import femap, stats"
I tried running this locally with a fresh install of cinnabar:

```
# packages in environment at /home/ialibay/software/mambaforge/install/envs/openfe:
#
# Name                    Version                   Build  Channel
cinnabar                  0.3.0              pyhd8ed1ab_0    conda-forge
```

and I'm getting an import error on `femap`

2023-10-23 07:55 UTC, richardjgowers commented
@IAlibay I suspect it might need a cinnabar release, I'll do it this morning

2023-11-03 21:04 UTC, IAlibay approved these changes
All works fine locally, thanks @hannahbaumann !

2023-11-03 21:20 UTC, merged